### PR TITLE
pug: Add the hostname for multiple systems

### LINKED ISSUE #4: Support for multiple installs
Hi.
I might have overlooked something central, but what is the multiple installs support like? Would the gists files be overwritten if the set of installed packages is not the same?

I have Arch installed on multiple machines, and does not necessary want the same set of installed packages distributed on all of them.

Would something as simple as:
```bash
PACMANFILE="$HOSTNAME-pacman-list.pkg"
AURFILE="$HOSTNAME-aur-list.pkg"
```
solve this?

### PR DESCRIPTION
**Pull request by HaoZeke**
Fixes https://github.com/Ventto/pug/issues/4.

Actually I adapted this from [pacmanity](https://github.com/alexchernokun/pacmanity) but yeah its a simple enough concept.

### CODE REVIEW

**Comment by mxmilkiib** [comment]
@Ventto; Any chance this could get merged? Ta!

**Comment by AdamSLevy** [comment]
I also would love to see this merged.

**Comment by Ventto** [comment]
@HaoZeke and all who have waited for this feature,
My apologies for the huge delay.

**Comment by ammgws** [comment]
@Ventto Could you please tag a new release? Otherwise this feature won't be available when installing from the AUR as shown in the project readme. In the meantime I've created a -git version of the package on the AUR at `pug-hook-git` (pug-git was taken by another unrelated tool)

**Pull request merged**
